# Configuración de Cloudflare Worker
name = "futbol-libre-hls-proxy"
main = "hls-proxy.js"
compatibility_date = "2024-01-01"

# Configuración de rutas
#routes = [
#  { pattern = "hls-proxy.tudominio.workers.dev/*", zone_name = "tudominio.com" }
#]

# Variables de entorno (opcional)
[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
