services:
  - type: web
    name: hls-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: VERCEL_CDN_URL
        value: https://futbol-libre.vercel.app
